/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.InterfazPrincipal;

import Vista.Cliente.I_GestionCliente;
import Vista.Producto.I_GestionProducto;
import Vista.OrdenCompra.I_GestionOrdenCompra;
import Vista.Proveedor.I_GestionProveedor;
import Vista.Reporte.I_GestionReporte;
import Vista.Trabajador.I_GestionTrabajador;
import Vista.Venta.I_GestionVenta;
import Vista.util.Interaccion;

/**
 *
 * @author HACK
 */
public class I_Admin extends javax.swing.JPanel {

    private I_Principal formPrincipal;

    /**
     * Creates new form IAdmin
     */
    public I_Admin(I_Principal formPrincipal) {
        initComponents();
        this.formPrincipal = formPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnGestionTrabajador = new javax.swing.JButton();
        btnGestionCliente = new javax.swing.JButton();
        btnGestionProducto = new javax.swing.JButton();
        btnGetionVenta = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(900, 500));

        btnGestionTrabajador.setText("GESTIÓN TRABAJADOR");
        btnGestionTrabajador.setPreferredSize(new java.awt.Dimension(200, 30));
        btnGestionTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionTrabajadorActionPerformed(evt);
            }
        });

        btnGestionCliente.setText("GESTIÓN CLIENTE");
        btnGestionCliente.setPreferredSize(new java.awt.Dimension(200, 30));
        btnGestionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionClienteActionPerformed(evt);
            }
        });

        btnGestionProducto.setText("GESTIÓN PRODUCTO");
        btnGestionProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        btnGestionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProductoActionPerformed(evt);
            }
        });

        btnGetionVenta.setText("GESTIÓN VENTA");
        btnGetionVenta.setPreferredSize(new java.awt.Dimension(200, 30));
        btnGetionVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetionVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(btnGetionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /*
    
    private void btnGestionTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        Interaccion.Gestion_ShowJPanel(new I_GestionTrabajador(), contenedor);
    }                                                    

    //Se fue
    private void btnGestionOrdenCompraActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        Interaccion.Gestion_ShowJPanel(new I_GestionOrdenCompra(), contenedor);
    }                                                     

    //Se fue
    private void btnGestionProveedorActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        Interaccion.Gestion_ShowJPanel(new I_GestionProveedor(), contenedor);
    }                                                   

    private void btnGetionVentaActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Interaccion.Gestion_ShowJPanel(new I_GestionVenta(), contenedor);
    }                                              

    private void btnGestionClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        Interaccion.Gestion_ShowJPanel(new I_GestionCliente(), contenedor);
    }                                                 

    private void btnGestionProductoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        Interaccion.Gestion_ShowJPanel(new I_GestionProducto(), contenedor);
    }           
    
    //Se fue
    private void btnGestionReporteActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        Interaccion.Gestion_ShowJPanel(new I_GestionReporte(), contenedor);
    }                                                 

     */
    private void btnGestionTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionTrabajadorActionPerformed
        Interaccion.Gestion_ShowJPanel(new I_GestionTrabajador(), contenedor);
    }//GEN-LAST:event_btnGestionTrabajadorActionPerformed

    private void btnGetionVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetionVentaActionPerformed
        Interaccion.Gestion_ShowJPanel(new I_GestionVenta(), contenedor);
    }//GEN-LAST:event_btnGetionVentaActionPerformed

    private void btnGestionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionClienteActionPerformed
        Interaccion.Gestion_ShowJPanel(new I_GestionCliente(), contenedor);
    }//GEN-LAST:event_btnGestionClienteActionPerformed

    private void btnGestionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProductoActionPerformed
        Interaccion.Gestion_ShowJPanel(new I_GestionProducto(), contenedor);
    }//GEN-LAST:event_btnGestionProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionCliente;
    private javax.swing.JButton btnGestionProducto;
    private javax.swing.JButton btnGestionTrabajador;
    private javax.swing.JButton btnGetionVenta;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
