/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.InterfazPrincipal;

import Vista.util.Interaccion;
import static Vista.util.Interaccion.Login_ShowJPanel;
import controlador.Usuario.CUsuario;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import modelos.MUsuario;

/**
 *
 * @author HACK
 */
public class I_Principal extends javax.swing.JFrame {

    // ------------- Variables -------------
    JButton btnCerrarSesion = null;
    private MUsuario user = null;
    private E_Acceso acceso;

    // ------------- END Variables -------------
    I_Admin menuAdmin = null;
    I_Vendedor menuVendedor = null;

    public I_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);

        btnCerrarSesion = new JButton("Cerrar Sesión");
        
        Interaccion.Login_ShowJPanel(new I_Login(this), contenedor, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(644, 292));
        setSize(new java.awt.Dimension(950, 500));

        contenedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contenedor.setPreferredSize(new java.awt.Dimension(950, 500));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Creates new form Principal
     */
    public void Agregar_I_Principal() {
        if (acceso == E_Acceso.LOGIN) {
            Interaccion.Login_ShowJPanel(new I_Login(this), contenedor, this);
        } else {
            switch (user.getIdTipoUsuario()) {
                case 1 -> {
                    menuAdmin = new I_Admin(this);
                    acceso = E_Acceso.ADMIN;
                    Interaccion.Principal_ShowJPanel(menuAdmin, contenedor, this, btnCerrarSesion);
                }
                case 2 -> {
                    menuVendedor = new I_Vendedor(this);
                    acceso = E_Acceso.EMPLEADO;
                    Interaccion.Principal_ShowJPanel(menuVendedor, contenedor, this, btnCerrarSesion);
                }

                default ->
                    JOptionPane.showMessageDialog(this, "No se encuentra el Form.");
            }
        } 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    // End of variables declaration//GEN-END:variables

    // --- Usuario ---
    public MUsuario getUser() {
        return user;
    }

    public void setUser(MUsuario user) {
        this.user = user;
    }

    // --- Tipo de Acceso ---
    public E_Acceso getAcceso() {
        return acceso;
    }

    public void setAcceso(E_Acceso acceso) {
        this.acceso = acceso;
    }

}
