/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Producto.CRUD;

import Vista.util.Mensaje;
import controlador.Producto.CProducto;
import controlador.Producto.IAgregarP;
import javax.swing.JOptionPane;
import modelos.E_TipoAccion;
import static modelos.E_TipoAccion.BUSCAR;
import static modelos.E_TipoAccion.NUEVA_BUSQUEDA;
import modelos.MProducto;

/**
 *
 * @author HACK
 */
public class I_AgregarProducto extends javax.swing.JPanel {

    IAgregarP cp = new CProducto(); //Controlador
    MProducto mp = new MProducto();

    E_TipoAccion accionInsecion = E_TipoAccion.AGREGAR;
    E_TipoAccion accionBusqueda = E_TipoAccion.BUSCAR;

    int stockActual = 0;

    /**
     * Creates new form I_AgregarCliente
     */
    public I_AgregarProducto() {
        initComponents();
        lblNumero.setText("N° Producto: " + cp.siguienteNumeroProducto());
        cp.listarCategoriaA(comboCategoria);
        cp.clearCamposAgregarP(this);
        cp.disableControl(txtIDBusqueda);
        cp.disableControl(btnBuscar_NuevaBusqueda);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        lblNumero = new javax.swing.JLabel();
        btnAgregar_Aumentar_Producto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chxAdicionar = new javax.swing.JCheckBox();
        txtIDBusqueda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBuscar_NuevaBusqueda = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Precio:");

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStock.setText("Stock:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Categoría:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Descripción:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        txtStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        comboCategoria.setEditable(true);
        comboCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStock, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(txtPrecio)
                    .addComponent(txtStock)
                    .addComponent(txtDescripcion)
                    .addComponent(comboCategoria, 0, 269, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumero.setText("N° Producto: ");

        btnAgregar_Aumentar_Producto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar_Aumentar_Producto.setText("Agregar producto");
        btnAgregar_Aumentar_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_Aumentar_ProductoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chxAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chxAdicionar.setText("Adicionar");
        chxAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxAdicionarActionPerformed(evt);
            }
        });

        txtIDBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIDBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDBusquedaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("ID: ");

        btnBuscar_NuevaBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar_NuevaBusqueda.setText("Buscar");
        btnBuscar_NuevaBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_NuevaBusqueda_NuevaBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(chxAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar_NuevaBusqueda)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chxAdicionar)
                    .addComponent(txtIDBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnBuscar_NuevaBusqueda))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumero)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 141, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(133, 133, 133))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar_Aumentar_Producto)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumero)
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnAgregar_Aumentar_Producto)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        mp.bloquearNoNumeroReal(evt, txtPrecio);
        mp.bloquearNumeroMenorACero(evt, txtPrecio);
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        mp.bloquearNoNumeroEntero(evt);
        mp.bloquearNumeroMenorACero(evt, txtStock);
    }//GEN-LAST:event_txtStockKeyTyped

    private void btnAgregar_Aumentar_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_Aumentar_ProductoActionPerformed
        mp = cp.asignarCamposAObjetoAgregarP(this);
        switch (accionInsecion) {
            case AGREGAR:
                int rowsAfected = cp.agregar(mp);
                if (rowsAfected > 0) {
                    cp.clearCamposAgregarP(this);
                    //cp.
                } else if (rowsAfected == -1) {
                    if (JOptionPane.YES_OPTION == Mensaje.CONFIRMACION("Este item ya existe. ¿Desea adicionar stock al item?")) {
                        cp.setEstablish(true, chxAdicionar);
                        checkAdicionar();
                        cp.setContent(cp.consultar(mp.getNombreProducto()).getIdProducto(), txtIDBusqueda);
                        Buscar_NuevaBusqueda();
                    }
                }
                break;

            case AUMENTAR:
                mp.setStockProducto(stockActual + cp.numberEntero(txtStock));
                if (cp.aumentar(mp) > 0) {
                    cp.clearCamposAgregarP(this);
                    Buscar_NuevaBusqueda();
                    cp.setEstablish(false, chxAdicionar);
                    checkAdicionar();
                    
                }
                break;
        }
    }//GEN-LAST:event_btnAgregar_Aumentar_ProductoActionPerformed

    private void txtPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyReleased
        mp.reactivarPuntoDecimal(evt, txtPrecio);
    }//GEN-LAST:event_txtPrecioKeyReleased

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        mp.bloquearCaracterEspecial_NoNumero_NoCaracter(evt);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtIDBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDBusquedaKeyTyped
        mp.bloquearNoNumeroEntero(evt);
    }//GEN-LAST:event_txtIDBusquedaKeyTyped

    private void checkAdicionar() {
        if (chxAdicionar.isSelected()) {
            accionInsecion = E_TipoAccion.AUMENTAR;
            cp.desabilitarControles(this);
            cp.enableControl(txtStock);
            cp.enableControl(txtIDBusqueda);
            cp.enableControl(btnBuscar_NuevaBusqueda);
            cp.setContent("Actualizar producto", btnAgregar_Aumentar_Producto);
            cp.setContent("Stock a adicionar:", lblStock);
            cp.focus(txtIDBusqueda);
        } else {
            accionInsecion = E_TipoAccion.AGREGAR;
            String campo = txtIDBusqueda.getText();
            cp.clearCamposAgregarP(this);
            txtIDBusqueda.setText(campo);
            cp.habilitarControles(this);
            cp.disableControl(txtIDBusqueda);
            cp.disableControl(btnBuscar_NuevaBusqueda);
            cp.setContent("Agregar producto", btnAgregar_Aumentar_Producto);
            cp.setContent("Stock:", lblStock);
            cp.focus(txtNombre);
        }
    }

    private void chxAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxAdicionarActionPerformed
        checkAdicionar();
    }//GEN-LAST:event_chxAdicionarActionPerformed

    
    
    private void Buscar_NuevaBusqueda() {
        switch (accionBusqueda) {
            case BUSCAR:
                mp = cp.consultar(txtIDBusqueda);
                if (mp != null) {
                    cp.asignarCamposFormAgregarP(this, mp);
                    cp.clear(txtStock);
                    stockActual = mp.getStockProducto();
                    cp.disableControl(txtIDBusqueda);
                    cp.setContent("Nueva Busqueda", btnBuscar_NuevaBusqueda);
                    cp.setContent("Actualizar producto", btnAgregar_Aumentar_Producto);
                    cp.focus(txtStock);
                    
                    accionBusqueda = E_TipoAccion.NUEVA_BUSQUEDA;
                }
                mp = new MProducto();
                break;

            case NUEVA_BUSQUEDA:
                cp.clearCamposAgregarP(this);
                cp.enableControl(txtIDBusqueda);
                cp.setContent("Buscar", btnBuscar_NuevaBusqueda);
                cp.setContent("Agregar producto", btnAgregar_Aumentar_Producto);
                
                cp.focus(txtIDBusqueda);
                
                accionBusqueda = E_TipoAccion.BUSCAR;
                break;
        }
    }

    private void btnBuscar_NuevaBusqueda_NuevaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_NuevaBusqueda_NuevaBusquedaActionPerformed

        Buscar_NuevaBusqueda();

    }//GEN-LAST:event_btnBuscar_NuevaBusqueda_NuevaBusquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar_Aumentar_Producto;
    private javax.swing.JButton btnBuscar_NuevaBusqueda;
    private javax.swing.JCheckBox chxAdicionar;
    public javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblStock;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtIDBusqueda;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
